# Generated by Django 3.2.6 on 2021-08-23 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsPaper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(through='NewsPaper.PostCategory', to='NewsPaper.Category', verbose_name='Категория'),
        ),
    ]
